wip

diff --git a/.github/workflows/build_wasm.yml b/.github/workflows/build_wasm.yml
--- a/.github/workflows/build_wasm.yml
+++ b/.github/workflows/build_wasm.yml
@@ -67,23 +67,25 @@ jobs:
             wasm-pack -v pack .
           '
 
-      - name: Check that yarn.lock hash matches freshly built package
-        working-directory: packages
-        run: |
-          new_hash=$(sha1sum sequent-core/pkg/sequent-core-0.1.0.tgz | awk '{printf $1}')
-          lock_hash=$(grep "file:./admin-portal/rust/sequent-core-" yarn.lock | awk -F'#' '{printf $2}' | tr -d '"')
-          echo "New build hash: $new_hash"
-          echo "yarn.lock hash: $lock_hash"
-          if [ -z "$new_hash" ] || [ -z "$lock_hash" ]; then
-            echo "Error: could not extract one or both hashes"
-            exit 1
-          fi
-          if [ "$new_hash" != "$lock_hash" ]; then
-            echo "Error: sequent-core WASM package is out of date."
-            echo "Run rebuild.sequent-core.full (VSCode task) or rebuild-sequent-core-full.sh and commit the results."
-            exit 1
-          fi
-          echo "Hashes match: sequent-core WASM is up to date"
+      # Note: Commented out because this doesn't work, probably because the paths in the devcontainer and the GitHub Action runner are different, so the hash of the built package doesn't match the hash in yarn.lock.
+      # Keeping the commented-out code here for now in case we want to revisit this approach in the future
+      # - name: Check that yarn.lock hash matches freshly built package
+      #   working-directory: packages
+      #   run: |
+      #     new_hash=$(sha1sum sequent-core/pkg/sequent-core-0.1.0.tgz | awk '{printf $1}')
+      #     lock_hash=$(grep "file:./admin-portal/rust/sequent-core-" yarn.lock | awk -F'#' '{printf $2}' | tr -d '"')
+      #     echo "New build hash: $new_hash"
+      #     echo "yarn.lock hash: $lock_hash"
+      #     if [ -z "$new_hash" ] || [ -z "$lock_hash" ]; then
+      #       echo "Error: could not extract one or both hashes"
+      #       exit 1
+      #     fi
+      #     if [ "$new_hash" != "$lock_hash" ]; then
+      #       echo "Error: sequent-core WASM package is out of date."
+      #       echo "Run rebuild.sequent-core.full (VSCode task) or rebuild-sequent-core-full.sh and commit the results."
+      #       exit 1
+      #     fi
+      #     echo "Hashes match: sequent-core WASM is up to date"
 
       - name: Set Node.js 20.x
         uses: actions/setup-node@v4
