✨ Enhance beyond release process
Parent issue: https://github.com/sequentech/meta/issues/1174

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,6 +5,7 @@
 name: Automated Release Process
 run-name: 'Automated Release Process'
 on:
+  push: # Remove this once merged to main. This way this new workflow will appear in the Actions tab
   workflow_dispatch:
     inputs:
       createMajorReleaseBranch:
@@ -32,6 +33,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       NEW_RELEASE_BRANCH: ${{ steps.CreateReleaseBranch.outputs.NEW_RELEASE_BRANCH }}
+      DEPLOYER_BRANCH: ${{ steps.CreateReleaseBranch.outputs.DEPLOYER_BRANCH }}
     steps:
     - name: Input Validation
       run: |
@@ -44,6 +46,12 @@ jobs:
         if [ "${{ github.event.inputs.createMajorReleaseBranch }}" = "true" ] || [ "${{ github.event.inputs.createMinorReleaseBranch }}" = "true" ]; then
           if [ "${{ github.ref }}" != "refs/heads/main" ]; then
             echo "Error: This action can only be triggered from the main branch"
+            exit 1
+          fi
+          # Check the preRelease input is false, otherwise, fail
+          if [ "${{ github.event.inputs.preRelease }}" = "true" ]; then
+            echo "Error: Pre-release is not supported for the first release on a new release branch. Please set preRelease to false"
+            echo "Warning: You can set preRelease to true for the subsequent releases on the release branch"
             exit 1
           fi
         fi
@@ -66,17 +74,30 @@ jobs:
       run: |
         releaseBranchVersion=""
         if [ "${{ github.event.inputs.createMajorReleaseBranch }}" = "true" ]; then
-          releaseBranchVersion=$(release-it -i major --release-version --git.getLatestTagFromAllRefs=true | tail -n 1)
+          releaseBranchVersion=$(release-it -i major --release-version --git.getLatestTagFromAllRefs --git.tagMatch=v[0-9]*\.[0-9]*\.[0-9]* --no-git.requireCommits | tail -n 1)
         elif [ "${{ github.event.inputs.createMinorReleaseBranch }}" = "true" ]; then
-          releaseBranchVersion=$(release-it -i minor --release-version --git.getLatestTagFromAllRefs=true | tail -n 1)
+          releaseBranchVersion=$(release-it -i minor --release-version --git.getLatestTagFromAllRefs --git.tagMatch=v[0-9]*\.[0-9]*\.[0-9]* --no-git.requireCommits | tail -n 1)
         fi
-        # Create the branch if createMajorReleaseBranch or createMinorReleaseBranch is true
-        if [ "${{ github.event.inputs.createMajorReleaseBranch }}" = "true" ] || [ "${{ github.event.inputs.createMinorReleaseBranch }}" = "true" ]; then
+
+        releaseBranchName="${{ github.ref_name }}"
+        # Check if releaseBranchVersion is not empty
+        if [ ! -z "$releaseBranchVersion" ]; then
           # Trim the patch version from $releaseBranchVersion
-          initialReleaseTag=v$releaseBranchVersion
           releaseBranchVersion=$(echo $releaseBranchVersion | cut -d. -f1,2)
           releaseBranchName="release/$releaseBranchVersion"
+        fi
+        echo DEPLOYER_BRANCH=$releaseBranchName | tee -a $GITHUB_ENV $GITHUB_OUTPUT
 
+        # Create the branch if createMajorReleaseBranch or createMinorReleaseBranch is true
+        if [ "${{ github.event.inputs.createMajorReleaseBranch }}" = "true" ] || [ "${{ github.event.inputs.createMinorReleaseBranch }}" = "true" ]; then
+          # Due to an incompatibility with the release-it, we can not create a new minor or major release branch from the main branch if the latest tag is a pre-release
+          latestRelease=$(git -c "versionsort.suffix=-" for-each-ref --count=1 --sort=-v:refname --format="%(refname:short)" refs/tags/v[0-9]*.[0-9]*.[0-9]*)
+          # Check if latestRelease contains "-rc."
+          if [[ $latestRelease == *-rc.* ]]; then
+            echo "Error: You can not create a new release branch from the main branch if the latest tag is a pre-release"
+            echo "Warning: Please release the pre-release version on the existing release branch before creating a new release branch"
+            exit 1
+          fi
           # Check if the branch already exists without failing
           branchExists=$(git ls-remote --heads origin $releaseBranchName)
           if [ -n "$branchExists" ]; then
@@ -87,9 +108,7 @@ jobs:
             git checkout -b $releaseBranchName
             # Add an empty commit to the new branch
             git commit --allow-empty -m "Release branch $releaseBranchName"
-            git tag $initialReleaseTag
             git push origin $releaseBranchName
-            git push origin --tags
           fi
           echo NEW_RELEASE_BRANCH=$releaseBranchName | tee -a $GITHUB_ENV $GITHUB_OUTPUT
         else
@@ -146,13 +165,16 @@ jobs:
         git commit -m "Preparation for release"
         git push origin HEAD
 
-        latestTag=$(git describe --tags --abbrev=0)
-        if [[ $latestTag == *-* ]]; then
-          echo "Latest tag is a pre-release"
-          echo "latestReleaseIsPreRelease=true" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
-        else
-          echo "Latest tag is not a pre-release"
-          echo "latestReleaseIsPreRelease=false" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
+        # Only check if the latest tag is a pre-release if NEW_RELEASE_BRANCH is empty
+        if [ "${{ needs.create-release-branch.outputs.NEW_RELEASE_BRANCH }}" == "" ]; then
+          latestTag=$(git describe --tags --abbrev=0)
+          if [[ $latestTag == *-* ]]; then
+            echo "Latest tag is a pre-release"
+            echo "latestReleaseIsPreRelease=true" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
+          else
+            echo "Latest tag is not a pre-release"
+            echo "latestReleaseIsPreRelease=false" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
+          fi
         fi
 
     - name: Release
@@ -161,17 +183,30 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         echo "Release Version (is prerelease: ${{ inputs.preRelease }}): ${{ steps.Release.outputs.VERSION }}"
-        if [ "${{ github.event.inputs.preRelease }}" = "true" ]; then
-          # Check if the latest tag is a pre-release
-          if [ "${{ steps.CheckLatestRelease.outputs.latestReleaseIsPreRelease }}" = "true" ]; then
-            # Then increment the pre-release version
-            release-it --ci --increment=pre --preRelease=rc
+
+        # If the new release branch is not created, then increment the patch version
+        if [ "${{ needs.create-release-branch.outputs.NEW_RELEASE_BRANCH }}" == "" ]; then
+          if [ "${{ github.event.inputs.preRelease }}" = "true" ]; then
+            # Check if the latest tag is a pre-release
+            if [ "${{ steps.CheckLatestRelease.outputs.latestReleaseIsPreRelease }}" = "true" ]; then
+              # Then increment the pre-release version
+              release-it --ci --increment=pre --preRelease=rc
+            else
+              release-it --ci --increment=patch --preRelease=rc
+            fi
           else
-            release-it --ci --increment=patch --preRelease=rc
+            release-it --ci --increment=patch
           fi
         else
-          release-it --ci --increment=patch --git.tagExclude=*[-]*
+          # If the new release branch is created, then increment the minor or major version
+          # Currently, no pre-release is supported for major or minor releases from the main branch
+          if [ "${{ github.event.inputs.createMajorReleaseBranch }}" = "true" ]; then
+            release-it --ci --increment=major --git.tagMatch=v[0-9]*\.[0-9]*\.[0-9]* --git.getLatestTagFromAllRefs
+          elif [ "${{ github.event.inputs.createMinorReleaseBranch }}" = "true" ]; then
+            release-it --ci --increment=minor --git.tagMatch=v[0-9]*\.[0-9]*\.[0-9]* --git.getLatestTagFromAllRefs
+          fi
         fi
+
         VERSION=$(git describe --tags --abbrev=0)
         echo VERSION=$VERSION | tee -a $GITHUB_ENV $GITHUB_OUTPUT
         echo HASH=$(git rev-parse --short $VERSION) | tee -a $GITHUB_ENV $GITHUB_OUTPUT
@@ -187,15 +222,43 @@ jobs:
       tag: ${{ needs.release.outputs.VERSION }}
       push: true
 
-  trigger-deployer:
+  trigger-beyond-release:
     needs: [release, build-and-push]
     runs-on: ubuntu-latest
     steps:
+    - name: Trigger Beyond Release Workflow
+      uses: the-actions-org/workflow-dispatch@v4 # https://github.com/the-actions-org/workflow-dispatch
+      with:
+        repo: 'sequentech/beyond'
+        ref: ${{ github.ref }}
+        workflow: 'Automated Release Process'
+        token: ${{ secrets.PAT }}
+        inputs: '{"createMajorReleaseBranch":${{ github.event.inputs.createMajorReleaseBranch }}, "createMinorReleaseBranch":${{ github.event.inputs.createMinorReleaseBranch }}, "preRelease":${{ github.event.inputs.preRelease }} }'
+        wait-for-completion: true
+
+  trigger-gitops-release:
+    needs: [release, build-and-push]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Trigger GitOps Release Workflow
+      uses: the-actions-org/workflow-dispatch@v4 # https://github.com/the-actions-org/workflow-dispatch
+      with:
+        repo: 'sequentech/gitops'
+        ref: ${{ github.ref }}
+        workflow: 'Automated Release Process'
+        token: ${{ secrets.PAT }}
+        inputs: '{"createMajorReleaseBranch":${{ github.event.inputs.createMajorReleaseBranch }}, "createMinorReleaseBranch":${{ github.event.inputs.createMinorReleaseBranch }}, "preRelease":${{ github.event.inputs.preRelease }} }'
+        wait-for-completion: true
+
+  trigger-deployer:
+    needs: [release, create-release-branch, build-and-push, trigger-beyond-release, trigger-gitops-release]
+    runs-on: ubuntu-latest
+    steps:
     - name: Trigger Deployer Workflow
-      uses: benc-uk/workflow-dispatch@v1.2.4
+      uses: the-actions-org/workflow-dispatch@v4 # https://github.com/the-actions-org/workflow-dispatch
       with:
         repo: sequentech/gitops
-        ref: ${{ needs.create-release-branch.outputs.NEW_RELEASE_BRANCH || github.ref }}
+        ref: ${{ needs.create-release-branch.outputs.DEPLOYER_BRANCH }}
         workflow: Deployer Workflow
         token: ${{ secrets.PAT }}
         inputs: '{"version":"${{ needs.release.outputs.VERSION }}", "hash":"${{ needs.release.outputs.HASH }}"}'
@@ -230,7 +293,7 @@ jobs:
           # Required Input
           repo_token: ${{secrets.GITHUB_TOKEN}}
           slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
-          # Optional Input 
+          # Optional Input
           name: 'Github Actions'
 
       - name: Slack additional info
