delete the release if workflow failed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -73,17 +73,20 @@ jobs:
           "${{ secrets.GH_API_URL }}" \
           --data '{"event_type": "new-release-trigger", "client_payload": {"version": "${{ needs.release.outputs.VERSION }}", "repository": "backend-services"}}'
 
-#TODO: post failure stage, undo / delete the release
-  # cleanup:
-  #   if: ${{ failure() }}
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
+  cleanup:
+    if: failure()
+    # Here define the depenency jobs
+    needs: [release,build-and-push]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 # Fetches all history for all tags and branches
 
-  #     - name: Delete Release
-  #       run: |
-  #         RELEASE_ID=$(gh release view "${{ github.ref }}" --json id -q '.id')
-  #         gh release delete $RELEASE_ID -y
-  #       env:
-  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Delete Release
+        run: |
+          echo "Version received in cleanup job: ${{ needs.release.outputs.VERSION }}"
+          gh release delete '${{ needs.release.outputs.VERSION }}' -y --cleanup-tag  || echo "Failed to delete release"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
